// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YandexSpeech;

#nullable disable

namespace YandexSpeech.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260715000000_AddGoogleCalendarDeclineTracking")]
    partial class AddGoogleCalendarDeclineTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new SnapshotInvoker().Invoke(modelBuilder);
#pragma warning restore 612, 618
        }

        private sealed class SnapshotInvoker : MyDbContextModelSnapshot
        {
            public void Invoke(ModelBuilder modelBuilder) => BuildModel(modelBuilder);
        }
    }
}
