using YoutubeExplode.Videos.ClosedCaptions;

namespace YandexSpeech.services;

public sealed record CaptionTrackOption(
    string Key,
    string LanguageCode,
    string LanguageName,
    bool IsAutoGenerated);

public static class CaptionTrackSelection
{
    public static IReadOnlyList<CaptionTrackOption> Describe(
        IReadOnlyList<ClosedCaptionTrackInfo> tracks)
    {
        var ordinals = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        var options = new List<CaptionTrackOption>(tracks.Count);

        foreach (var track in tracks)
        {
            var prefix = $"{track.Language.Code.ToLowerInvariant()}|{(track.IsAutoGenerated ? "auto" : "manual")}";
            ordinals.TryGetValue(prefix, out var ordinal);
            ordinals[prefix] = ordinal + 1;
            options.Add(new CaptionTrackOption(
                $"{prefix}|{ordinal}",
                track.Language.Code,
                track.Language.Name,
                track.IsAutoGenerated));
        }

        return options;
    }

    public static ClosedCaptionTrackInfo? Find(
        IReadOnlyList<ClosedCaptionTrackInfo> tracks,
        string key)
    {
        var options = Describe(tracks);
        for (var i = 0; i < options.Count; i++)
        {
            if (string.Equals(options[i].Key, key, StringComparison.OrdinalIgnoreCase))
                return tracks[i];
        }

        return null;
    }
}
